service: software-engineer-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getQuiz:
    handler: src/application_layer/getQuiz.handler
    events:
      - httpApi:
          path: /
          method: get
  validateAnswer:
    handler: src/application_layer/validateAnswer.validate
    events:
      - httpApi:
          path: /
          method: post


plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9090
