service: software-engineer-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get


plugins:
  - serverless-esbuild
  - serverless-offline
